database:
  databases:
    - "CTDChemical"
    - "CTDGene"
    - "CTDAssociations"
    - "Reactome"
    - "PathwayCommons"
  sources:
    Chemical: "CTDChemical"
    Gene: "CTDGene"
    Pathway: "Reactome"
    Disease: "DO"

ontology:
  ontologies:
    "Disease": "DO"
    "Tissue": "BTO"
    "Clinical_variable": "SNOMED-CT"
    "Phenotype": "HPO"
    "Experiment": "PSI-MS"
    "Modification": "PSI-MOD"
    "Molecular_interactions": "PSI-MI"
    "Gene_ontology": "GO"
    "Experimental_factor": "EFO"
    "Units": "UO"
    #'Biomedical_investigations': 'OBI'
    #'Diagnosis': 'ICD-10'

  entities:
    "DO": "Disease"
    "BTO": "Tissue"
    "SNOMED-CT": "Clinical_variable"
    "HPO": "Phenotype"
    "PSI-MS": "Experiment"
    "PSI-MOD": "Modification"
    "PSI-MI": "Molecular_interaction"
    "biological_process": "Biological_process"
    "molecular_function": "Molecular_function"
    "cellular_component": "Cellular_component"
    "EFO": "Experimental_factor"
    "unit.ontology": "Units"
    #'OBI': 'Biomedical_investigations'
    #'ICD-10': 'Diagnosis'

  ontology_types:
    "DO": "-26"
    "BTO": "-25"
    "SNOMED-CT": "-40"
    "PSI-MOD": "-41"
    "PSI-MS": "-42"
    "PSI-MI": "-43"
    "HPO": "-44"
    "SMASH": "-42"
    "GO": "-21"
    "EFO": "-45"
    "UO": "-46"
    #'OBI':  '-47'
    #'ICD-10': '-48'

  parser_filters:
    "-40":
      - "308916002"
      - "363787002"
      - "373873005"
      - "71388002"
      - "48176007"
      - "105590001"

  urls:
    "-26":
      - "http://purl.obolibrary.org/obo/doid.obo"
    "-25":
      - "http://data.bioontology.org/ontologies/BTO/submissions/33/download?apikey=8b5b7825-538d-40e0-9e9e-5ab9274a9aeb"
    "-21":
      - "http://purl.obolibrary.org/obo/go.obo"
    "-41":
      - "https://github.com/HUPO-PSI/psi-mod-CV/raw/master/PSI-MOD.obo"
    "-42":
      - "https://github.com/HUPO-PSI/psi-ms-CV/raw/master/psi-ms.obo"
    "-43":
      - "https://raw.githubusercontent.com/HUPO-PSI/psi-mi-CV/master/psi-mi.obo"
    "-44":
      - "http://purl.obolibrary.org/obo/hp.obo"
      #- 'http://compbio.charite.de/jenkins/job/hpo.annotations/lastStableBuild/artifact/misc/phenotype_annotation.tab'
      #- 'http://compbio.charite.de/jenkins/job/hpo.annotations/lastStableBuild/artifact/util/annotation/genes_to_phenotype.txt'
    "-45":
      - "https://www.ebi.ac.uk/efo/efo.obo"
    "-46":
      - "https://raw.githubusercontent.com/bio-ontology-research-group/unit-ontology/master/unit.obo"
    #'-47':
    #    - https://raw.githubusercontent.com/obi-ontology/obi/v2020-04-23/views/obi.obo
    #'-48':
    #    - 'ftp://ftp.cdc.gov/pub/Health_Statistics/NCHS/Publications/ICD10CM/2020/icd10cm_codes_2020.txt'

  files:
    "-40":
      - "SNOMED-CT/Full/Terminology/sct2_Concept_Full_INT_*.txt"
      - "SNOMED-CT/Full/Terminology/sct2_Description_Full-en_INT_*.txt"
      - "SNOMED-CT/Full/Terminology/sct2_Relationship_Full_INT_*.txt"
      - "SNOMED-CT/Full/Terminology/sct2_TextDefinition_Full-en_INT_*.txt"
