name: Deploy Studio
on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master

      - name: install
        run: cd studio && yarn

      # - name: plugins
      #   run: yarn add umi-plugin-pro

      # - name: fetch-blocks
      #   run: yarn run pro fetch-blocks

      - name: site
        run: cd studio && npm run build
        env:
          NODE_ENV: production

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./studio/dist
          force_orphan: true
